import { Meaning } from './types';

export const LETTER_VALUES: Record<string, number> = {
  'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7, 'H': 8, 'I': 9,
  'J': 1, 'K': 2, 'L': 3, 'M': 4, 'N': 5, 'Ñ': 5, 'O': 6, 'P': 7, 'Q': 8, 'R': 9,
  'S': 1, 'T': 2, 'U': 3, 'V': 4, 'W': 5, 'X': 6, 'Y': 7, 'Z': 8
};

export const VOWELS = ['A', 'E', 'I', 'O', 'U'];

export const LIFE_PATH_MEANINGS: Record<number, Meaning> = {
  1: {
    meaning: "Tu Camino de Vida 1 te marca como un 'Pionero'. Tu misión es desarrollar tu independencia, tu coraje y tu capacidad de liderazgo. Has venido a aprender a confiar en tu propia voz y a abrir nuevos caminos para ti y para los demás. Eres una fuerza de inicio, con una energía creativa que busca constantemente manifestarse. Tu alma anhela la originalidad y la autosuficiencia, y te sientes más pleno cuando tomas la iniciativa y confías en tu singularidad para guiar tus pasos en el mundo.",
    lightAndShadow: "En luz, eres un líder carismático, innovador y valiente. En sombra, esta misma fuerza puede volverse arrogancia, egoísmo e impaciencia. Puedes tender a ser dominante y a sentirte aislado si no aprendes a colaborar. El desafío es liderar sin imponer, compartiendo tu luz sin dejar que tu ego te ciegue ante las valiosas contribuciones de los demás.",
    tip: "Comprométete a iniciar un proyecto personal que te apasione profundamente. Practica la toma de decisiones confiando en tu instinto, incluso si eso significa ir en contra de la corriente. Dedica tiempo a estar solo para fortalecer tu conexión contigo mismo, pero también busca activamente oportunidades para escuchar y valorar las ideas de otros. El verdadero liderazgo nace de la autoconfianza, no de la necesidad de controlar."
  },
  2: {
    meaning: "Tu Camino de Vida 2 te identifica como el 'Diplomático'. Tu misión es aprender sobre la cooperación, la paciencia y el equilibrio en las relaciones. Vienes a ser un pacificador, a unir a las personas y a cultivar la armonía en tu entorno. Tu sendero implica desarrollar tu intuición y sensibilidad, aprendiendo a ser un apoyo para los demás sin perderte a ti mismo. Tu alma busca la conexión y la seguridad emocional, encontrando su mayor fortaleza en la colaboración y el trabajo en equipo.",
    lightAndShadow: "En luz, eres empático, adaptable y un mediador excepcional. Tu paz y lealtad te convierten en un amigo y socio invaluable. En sombra, puedes volverte hipersensible, dependiente y temeroso del conflicto. Tu deseo de agradar puede llevarte a la indecisión y a reprimir tus propias necesidades, generando resentimiento. El desafío es mantener tu naturaleza compasiva sin permitir que otros abusen de tu amabilidad.",
    tip: "Establece límites claros y amorosos en tus relaciones. Aprende a decir 'no' cuando sea necesario, entendiendo que es un acto de autorespeto. Confía en tu poderosa intuición; es tu mejor guía. Participa en actividades grupales donde tu habilidad para armonizar sea un activo. Dedica tiempo a nutrir tu mundo interior a través del arte o la meditación para fortalecer tu centro emocional y no depender de la validación externa."
  },
  3: {
    meaning: "Un Camino de Vida 3 te señala como el 'Comunicador'. Tu misión es expresar tu verdad creativa y traer alegría al mundo. Vienes a aprender a usar tu voz, ya sea hablada, escrita o artística, para inspirar y elevar a los demás. Tu sendero está lleno de sociabilidad, optimismo y una necesidad innata de autoexpresión. El universo te pide que abraces tu imaginación y no temas mostrar tu lado más lúdico y carismático. Tu alma se nutre de la belleza y la conexión humana.",
    lightAndShadow: "En tu aspecto luminoso, eres creativo, encantador y optimista, con un don natural para la comunicación. En sombra, puedes caer en la dispersión, la superficialidad y el drama. Tu necesidad de atención puede llevarte a exagerar o a usar tus palabras para herir. El desafío es enfocar tu energía creativa y comunicar desde el corazón, evitando la crítica y el chisme.",
    tip: "Elige un canal creativo (escribir, pintar, cantar) y comprométete a desarrollarlo con disciplina. Practica la comunicación consciente: antes de hablar, pregúntate si tus palabras son verdaderas, amables y necesarias. Lleva un diario para organizar tus ideas y conectar con tus emociones auténticas. Rodéate de personas que celebren tu alegría y te inspiren, y no temas mostrar tu vulnerabilidad."
  },
  4: {
    meaning: "Tu Camino de Vida 4 te define como el 'Constructor'. Tu misión es crear bases sólidas, estabilidad y orden en tu vida y en la de los demás. Vienes a aprender el valor del trabajo duro, la disciplina y la perseverancia. Tu sendero requiere un enfoque práctico y metódico para construir tus sueños paso a paso. Eres la columna vertebral de cualquier proyecto o familia, aportando seguridad y confianza. Tu alma anhela la estructura y la fiabilidad.",
    lightAndShadow: "En luz, eres increíblemente trabajador, honesto y confiable. Tu disciplina y enfoque te permiten alcanzar metas que para otros parecen imposibles. En sombra, puedes volverte rígido, terco y demasiado cauteloso, resistiéndote al cambio por miedo a perder el control. El desafío es ser flexible y aprender que la verdadera seguridad viene de la adaptabilidad, no solo de la rigidez.",
    tip: "Crea planes detallados para tus metas, pero permítete desviarte del plan cuando surjan nuevas oportunidades. Incorpora prácticas que fomenten la flexibilidad, como el yoga. Dedica tiempo al descanso y al ocio para evitar el agotamiento; tu valor no se mide solo por tu productividad. Aprende a delegar y a confiar en los demás. Disfruta del proceso de construcción tanto como del resultado final."
  },
  5: {
    meaning: "Un Camino de Vida 5 te marca como el 'Aventurero'. Tu misión es experimentar la vida en toda su diversidad y aprender a través del cambio y la libertad. Vienes a romper con la rutina, a adaptarte a lo inesperado y a usar tus experiencias para expandir tu conciencia. Tu sendero es dinámico y requiere versatilidad, curiosidad y valentía para explorar lo desconocido. Tu alma anhela la libertad de movimiento, pensamiento y expresión. Eres un agente de cambio.",
    lightAndShadow: "En tu luz, eres adaptable, carismático y magnético. Amas la aventura y aprendes rápido de cada experiencia. En sombra, tu anhelo de libertad puede convertirse en irresponsabilidad y falta de compromiso. Puedes caer en los excesos y la impaciencia, buscando constantemente el siguiente estímulo sin profundizar en nada. El desafío es encontrar la libertad dentro de la disciplina.",
    tip: "Viaja, aprende nuevos idiomas o explora diferentes culturas para satisfacer tu curiosidad de manera constructiva. Elige un área de interés y comprométete a profundizar en ella. Practica el mindfulness para aprender a disfrutar del momento presente en lugar de buscar siempre la próxima aventura. Establece rutinas saludables que te den una base estable desde la cual explorar el mundo."
  },
  6: {
    meaning: "Tu Camino de Vida 6 te designa como el 'Nutridor'. Tu misión es aprender sobre la responsabilidad, el amor y el servicio, especialmente en el ámbito del hogar y la comunidad. Vienes a crear belleza y armonía, y a cuidar de los demás con un corazón compasivo. Tu sendero implica equilibrar el dar y el recibir, y aprender a sanar a otros sin sacrificar tu propio bienestar. Eres un consejero y protector nato, y tu alma encuentra su mayor alegría en el servicio.",
    lightAndShadow: "En luz, eres amoroso, responsable y compasivo, un verdadero pilar para tu familia y comunidad. En sombra, puedes volverte controlador y entrometido, creyendo que sabes lo que es mejor para todos. Puedes caer en el perfeccionismo o convertirte en un mártir que se sacrifica en exceso. El desafío es amar y servir sin imponer, y cuidar de ti mismo con la misma dedicación.",
    tip: "Crea un hogar que sea tu santuario de paz y belleza. Ofrece tu ayuda y consejo, pero aprende a soltar el resultado. Inicia una práctica de autocuidado que sea innegociable. Aprende a recibir ayuda y afecto, permitiendo que otros también cuiden de ti. Tu capacidad de amar es inmensa; asegúrate de dirigir una buena parte de ese amor hacia ti mismo."
  },
  7: {
    meaning: "Un Camino de Vida 7 te señala como el 'Sabio'. Tu misión es buscar la verdad, el conocimiento y la conexión espiritual a través de la introspección y el análisis. Vienes a este mundo a confiar en tu intuición y a compartir tu sabiduría única. Tu sendero es el del investigador y el místico, y requiere que pases tiempo a solas para conectar con tu mundo interior. Tu alma anhela la profundidad y la comprensión de los misterios de la vida.",
    lightAndShadow: "En tu aspecto luminoso, eres sabio, intuitivo y analítico, con una mente brillante. En sombra, tu necesidad de soledad puede llevarte al aislamiento, la desconfianza y la frialdad emocional. Puedes volverte cínico, sarcástico y parecer arrogante. El desafío es equilibrar tu rico mundo interior con el mundo exterior, aprendiendo a compartir tu sabiduría sin alejar a los demás.",
    tip: "Establece una práctica diaria de meditación o reflexión. Pasa tiempo en la naturaleza. Confía en los destellos de tu intuición y actúa en consecuencia. Encuentra un círculo pequeño de personas de confianza con quienes puedas compartir tus pensamientos más profundos. Estudia temas que te fascinen y considera enseñar o escribir sobre ellos para compartir tu conocimiento."
  },
  8: {
    meaning: "Tu Camino de Vida 8 te define como el 'Poderoso'. Tu misión es aprender a manejar el poder, la abundancia y la autoridad en el mundo material de una manera equilibrada y ética. Vienes a ser un líder en el ámbito de los negocios o las finanzas, aprendiendo a manifestar grandes logros. Tu sendero implica superar desafíos relacionados con el dinero y el control, y usar tu fuerza para empoderar a otros. Tu alma busca la maestría en el plano terrenal.",
    lightAndShadow: "En luz, eres un líder visionario, ambicioso y con una gran capacidad para la ejecución. Eres justo y organizado. En sombra, puedes volverte autoritario, controlador y excesivamente materialista. Tu ambición puede llevarte a ser intolerante y a trabajar en exceso. El desafío es usar tu poder para servir y construir, en lugar de para dominar.",
    tip: "Establece metas financieras claras que estén alineadas con un propósito mayor. Practica la generosidad. Aprende a delegar y a empoderar a otros. Equilibra tu trabajo con actividades que nutran tu alma y tus relaciones personales. Sé un ejemplo de liderazgo ético, donde el éxito se mide no solo por las ganancias, sino también por el impacto positivo."
  },
  9: {
    meaning: "Un Camino de Vida 9 te designa como el 'Humanitario'. Tu misión está ligada al servicio desinteresado, la compasión y una profunda preocupación por el bienestar colectivo. Vienes a este mundo a completar un ciclo, a aprender a soltar y a entregar tu sabiduría con generosidad. Posees una visión global y te sientes impulsado a dejar el mundo mejor de como lo encontraste. Tu alma resuena con el idealismo y el arte.",
    lightAndShadow: "En tu luz, eres increíblemente compasivo, generoso y altruista. Eres un alma vieja, sabia y tolerante. En tu sombra, puedes caer en el resentmento si sientes que tus sacrificios no son valorados, convirtiéndote en un mártir. Puedes sentirte abrumado por los problemas del mundo. El desafío es dar sin esperar nada a cambio y aprender a soltar el pasado.",
    tip: "Involúcrate en causas humanitarias o voluntariado que resuenen contigo. Practica el desapego a través de la meditación o el mindfulness. Expresa tus emociones a través de canales artísticos. Aprende a poner límites saludables para no agotarte emocionalmente y recuerda que tu mayor servicio es mantener tu propia luz brillando intensamente."
  },
  11: {
    meaning: "Tu Camino de Vida 11 te marca como el 'Maestro Intuitivo'. Esta es una vibración maestra con un potencial espiritual inmenso pero también mayores desafíos. Tu misión es inspirar a la humanidad a través de tu elevada intuición y tu conexión con los reinos sutiles. Eres un canal para la revelación y la verdad. Tu sendero requiere que confíes plenamente en tu guía interior y que aprendas a vivir en el mundo material sin perder tu conexión espiritual.",
    lightAndShadow: "En luz, eres un visionario, un sanador y un artista inspirado, con una capacidad casi psíquica. En sombra, la intensidad de esta energía puede generar una gran tensión nerviosa, ansiedad y dudas. Puedes sentirte incomprendido y tender al fanatismo o a evadir la realidad. El desafío es anclar tu elevada visión en la realidad práctica y aprender a manejar tu sistema nervioso sensible.",
    tip: "Establece una práctica diaria de meditación para calmar tu mente y afinar tu intuición. Pasa tiempo en la naturaleza para enraizar tu energía. Confía en tus corazonadas. Busca salidas creativas para canalizar la inspiración que recibes. Rodéate de un entorno tranquilo y de personas que apoyen tu sensibilidad. No tengas miedo de compartir tu luz única con el mundo."
  },
  22: {
    meaning: "Un Camino de Vida 22 te designa como el 'Maestro Constructor'. Esta es la vibración más poderosa para la manifestación en el plano material. Tu misión es tomar sueños e ideales espirituales y convertirlos en una realidad tangible que beneficie a la humanidad. Eres el 'arquitecto' del alma. Tu sendero combina la visión idealista del 11 con la capacidad práctica del 4. Vienes a aprender a manejar un poder inmenso con disciplina y responsabilidad.",
    lightAndShadow: "En tu luz, eres un líder pragmático y visionario, capaz de lograr hazañas extraordinarias. En sombra, la presión de este potencial puede ser abrumadora, llevándote a usar tu poder para fines egoístas o manipuladores. Puedes volverte terco o sentir que la carga es demasiado pesada. El desafío es mantenerte conectado a un propósito de servicio mientras construyes tus sueños.",
    tip: "Piensa en grande pero actúa paso a paso. Divide tus grandes visiones en metas pequeñas y manejables. Aprende sobre gestión de proyectos y liderazgo. Colabora con otros; no tienes que construirlo todo solo. Mantén una práctica espiritual que te recuerde constantemente el 'para qué' de tus esfuerzos, asegurando que tus ambiciones estén al servicio de un bien mayor."
  },
  33: {
    meaning: "Tu Camino de Vida 33 te marca como el 'Maestro del Amor'. Esta vibración maestra te llama a una vida de servicio desinteresado y sanación a través del amor incondicional. Tu misión es ser un faro de compasión, alegría y responsabilidad, elevando la conciencia de quienes te rodean. Eres la encarnación de la energía crística, combinando la creatividad del 3 con la responsabilidad nutridora del 6. Tu sendero es el del sanador y el maestro espiritual.",
    lightAndShadow: "En luz, eres una fuente de amor y sanación para el mundo. Tu compasión no tiene límites. En sombra, la carga de la responsabilidad puede ser inmensa, llevándote a convertirte en un mártir que se descuida a sí mismo por los demás. Puedes volverte perfeccionista y controlador en tu afán de 'arreglar' a todos. El desafío es servir desde la plenitud, no desde el sacrificio.",
    tip: "Enfócate primero en tu propia sanación y amor propio; no puedes dar lo que no tienes. Establece límites muy claros para proteger tu energía. Utiliza tus dones creativos como una forma de canalizar tu energía sanadora. Practica el perdón. Encuentra alegría en las pequeñas cosas y compártela. Tu misión no es cargar con el mundo, sino mostrarle al mundo cómo vivir con un corazón abierto."
  }
};

// Soul Numbers
export const SOUL_NUMBER_MEANINGS: Record<number, Meaning> = {
  1: {
    meaning: "Un Número de Alma 1 indica que tu deseo más profundo es ser independiente, original y el número uno en lo que haces. Anhelas liderar y ser reconocido por tus propios méritos. Tu motivación interna proviene de la necesidad de autoexpresión y de probar tu valía. No te sientes cómodo siguiendo órdenes; tu alma necesita la libertad para iniciar, crear y dirigir. Buscas constantemente desafíos que te permitan demostrar tu coraje y tu fuerza de voluntad.",
    lightAndShadow: "En luz, esta energía te impulsa a ser un pionero valiente y un líder innovador. En sombra, tu deseo de ser el primero puede convertirse en egoísmo, arrogancia y una renuencia a pedir ayuda. Puedes sentirte solo en la cima y tener dificultades para trabajar en equipo. El desafío es liderar con humildad y reconocer que la verdadera fuerza también reside en la capacidad de conectar y colaborar con los demás.",
    tip: "Date permiso para emprender proyectos en solitario que te apasionen. Establece metas personales ambiciosas y celebra cada logro. Practica la toma de decisiones basada en tu propia intuición, fortaleciendo la confianza en ti mismo. Al mismo tiempo, busca conscientemente oportunidades para colaborar, aprendiendo a liderar inspirando en lugar de imponiendo. Reconoce y elogia los talentos de los demás para equilibrar tu energía individualista."
  },
  2: {
    meaning: "Tu Número de Alma 2 revela que tu deseo más profundo es la unión, la armonía y el amor. Eres un alma sensible que anhela la conexión y la cooperación. Tu motivación interna proviene de crear paz y equilibrio en tus relaciones y en tu entorno. No buscas el protagonismo, sino ser parte de un equipo, apoyar y ser apoyado. La seguridad emocional y sentirte comprendido son fundamentales para tu bienestar.",
    lightAndShadow: "En luz, tu alma es empática, diplomática y extremadamente leal. En sombra, esta necesidad de armonía puede llevarte a una excesiva dependencia de los demás y a un miedo paralizante al conflicto. Puedes volverte indecisos y sacrificar tus propias necesidades para complacer a otros, guardando resentimiento en silencio. Tu sensibilidad puede hacerte vulnerable a las críticas.",
    tip: "Practica el arte de establecer límites saludables; aprende que decir 'no' es un acto de amor propio. Confía en tu poderosa intuición como tu principal consejera. Busca actividades donde puedas colaborar sin perder tu individualidad. Dedica tiempo a solas para conectar con tus propios sentimientos y deseos."
  },
  3: {
    meaning: "Con un Número de Alma 3, tu anhelo más profundo es la autoexpresión, la creatividad y la alegría. Tu alma desea comunicar y conectar con los demás de una manera lúdica y optimista. Te motiva la belleza, el arte y la capacidad de inspirar a otros con tus ideas y tu entusiasmo. Necesitas un canal para tu imaginación fértil. La vida, para ti, debe ser una celebración.",
    lightAndShadow: "En su aspecto luminoso, tu alma es vibrante, sociable y artísticamente dotada. En sombra, este deseo de expresión puede volverse superficial y disperso. Puedes temer la soledad y buscar constantemente la validación externa, cayendo en el drama o el chisme. Tu optimismo puede ser una máscara para evitar enfrentar emociones más profundas.",
    tip: "Encuentra una salida creativa y practícala regularmente como una necesidad espiritual. Lleva un diario para explorar tus sentimientos más allá de la superficie. Rodéate de personas que te permitan ser tú mismo. Aprende a disfrutar de momentos de silencio y soledad para recargar tu energía creativa. Usa tu don de la comunicación para elevar a otros."
  },
  4: {
    meaning: "Un Número de Alma 4 indica que tu deseo más profundo es la estabilidad, la seguridad y el orden. Tu alma anhela construir algo sólido y duradero en el mundo. Te motiva la necesidad de tener una base firme, tanto en tu hogar como en tu trabajo. Eres una persona que valora la estructura, la disciplina y la planificación. Tu corazón encuentra paz en la rutina y en la sensación de control que proviene de un trabajo bien hecho.",
    lightAndShadow: "En luz, esta energía te convierte en una persona increíblemente confiable, trabajadora y perseverante. En sombra, tu necesidad de seguridad puede volverte rígido, inflexible y resistente al cambio. Puedes caer en la terquedad y en una visión limitada de la vida, temiendo todo lo que no puedes controlar.",
    tip: "Crea rutinas que te apoyen pero que también incluyan espacio para la flexibilidad. Trabaja en proyectos que te permitan construir algo tangible, como la jardinería. Aprende a equilibrar el trabajo con el descanso. Practica la apertura a nuevas ideas. Confía en el proceso y entiende que la verdadera seguridad es la capacidad de adaptarte con una base sólida."
  },
  5: {
    meaning: "Si tu Número de Alma es 5, tu deseo más profundo es la libertad, la aventura y la experiencia sensorial. Tu alma anhela vivir la vida al máximo, sin restricciones ni ataduras. Te motiva la curiosidad, el cambio y la emoción de lo nuevo. Necesitas variedad y estimulación constante para sentirte vivo. Buscas la libertad en todos los aspectos de tu vida.",
    lightAndShadow: "En su vibración luminosa, tu alma es adaptable, versátil y carismática. En sombra, este anhelo de libertad puede llevarte a la falta de compromiso, la inconsistencia y la irresponsabilidad. Puedes caer en la búsqueda de placeres momentáneos y excesos, huyendo de cualquier situación que requiera profundidad.",
    tip: "Canaliza tu amor por la variedad de manera constructiva. Viaja, lee y aprende constantemente. Encuentra una disciplina física que te permita sentirte libre en tu cuerpo. Aprende a encontrar la libertad dentro del compromiso, eligiendo relaciones y proyectos que te permitan crecer. Practica el mindfulness para disfrutar del aquí y ahora."
  },
  6: {
    meaning: "Un Número de Alma 6 revela que tu deseo más profundo es el amor, la armonía y la responsabilidad familiar y comunitaria. Tu alma anhela cuidar, nutrir y crear belleza en tu entorno. Te motiva la necesidad de sentirte útil y de servir a tus seres queridos. El hogar y la familia son el centro de tu universo emocional. Buscas relaciones estables y comprometidas.",
    lightAndShadow: "En luz, tu alma es amoroso, compasivo y protector. En sombra, tu deseo de cuidar puede volverse controlador y entrometido. Puedes caer en el perfeccionismo y la ansiedad, o convertirte en un mártir que se sacrifica en exceso y luego se siente resentido. El desafío es cuidar sin asfixiar.",
    tip: "Enfócate en crear un hogar que sea un verdadero refugio de paz. Ofrece tu apoyo a los demás, pero practica el desapego del resultado. Aprende a cuidarte a ti mismo con la misma dedicación. Permite que otros te ayuden y te cuiden también. Expresa tu amor por la belleza a través del arte, la decoración o la jardinería."
  },
  7: {
    meaning: "Con un Número de Alma 7, tu ser más íntimo anhela la sabiduría, la verdad y la comprensión profunda del universo. Eres un alma investigadora que no se conforma con respuestas superficiales. Tu mayor motivación es desentrañar los misterios de la vida. Necesitas pasar tiempo a solas para recargar energías, procesar información y conectar con tu mundo interior. La soledad es tu santuario.",
    lightAndShadow: "En su vibración de luz, tu alma es sabia, intuitiva y analítica. En sombra, esta necesidad de soledad puede convertirse en aislamiento y frialdad emocional. Puedes volverte escéptico, cínico y desconfiado de los demás. Tu mente analítica puede llevarte a pensar en exceso y a desconectarte de tus sentimientos.",
    tip: "Crea un espacio sagrado en tu hogar para la meditación, la lectura y la reflexión. Confía y desarrolla tu intuición. Pasa tiempo en la naturaleza para calmar tu mente. Aunque valores la soledad, esfuérzate por compartir tus descubrimientos con un círculo íntimo de confianza. Esto te ayudará a equilibrar tu mundo interior con el exterior."
  },
  8: {
    meaning: "Si tu Número de Alma es 8, tu deseo más profundo es el poder, el éxito y la maestría en el mundo material. Tu alma anhela el control de tu propio destino y la capacidad de manifestar grandes logros. Te motiva la ambición, el reconocimiento y la búsqueda de la abundancia. No te asustan los desafíos; al contrario, los buscas como una forma de probar tu fuerza.",
    lightAndShadow: "En luz, esta energía te convierte en un líder nato, con una gran visión para los negocios y una capacidad impresionante para la ejecución. En sombra, tu deseo de poder puede volverte dominante, intolerante y materialista. Puedes tener una actitud de 'el fin justifica los medios' y volverte adicto al trabajo. El miedo a la escasez puede llevarte a ser controlador.",
    tip: "Define el éxito en tus propios términos, asegurándote de que incluya bienestar emocional y relaciones saludables. Practica la generosidad. Aprende a delegar y a empoderar a tu equipo. Equilibra tu ambición con actividades que te conecten con tu lado más vulnerable y humano. Usa tu poder para construir, no para controlar."
  },
  9: {
    meaning: "Un Número de Alma 9 indica que tu deseo más profundo es el servicio a la humanidad y la compasión universal. Tu alma anhela dejar un impacto positivo en el mundo. Te motiva un profundo idealismo y un sentido de conexión con todos los seres vivos. No buscas el beneficio personal, sino el bienestar colectivo. Tienes un corazón generoso y sientes el dolor del mundo como propio.",
    lightAndShadow: "En su aspecto luminoso, tu alma es compasiva, altruista y sabia. En sombra, puedes sentirte abrumado por el sufrimiento del mundo, lo que te lleva a la melancolía o al escapismo. Puedes tener dificultades para recibir y para poner límites, sacrificándose hasta el punto del agotamiento y el resentimiento.",
    tip: "Elige una causa que te apasione y contribuye de una manera que te resulte sostenible. Aprende a poner límites saludables. Practica el recibir con gratitud; mereces tanto amor como el que das. Dedica tiempo a actividades creativas que te permitan procesar tus profundas emociones. Recuerda que tu mayor contribución es mantener tu propia vibración alta."
  },
  11: {
    meaning: "Con un Número de Alma 11, tu deseo más profundo es la iluminación espiritual y la inspiración. Esta es una vibración maestra; tu alma no se conforma con lo mundano, anhela conectar con planos superiores de conciencia. Te motiva la búsqueda de la verdad y la revelación. Eres un soñador y un idealista. Tu corazón se siente vivo cuando actúas como un canal para la inspiración.",
    lightAndShadow: "En luz, tu alma es un faro de intuición y visión. En sombra, la intensidad de esta energía puede causar una gran tensión nerviosa y ansiedad. Puedes sentirte incomprendido y desconectado de la realidad, viviendo en un mundo de fantasía. El desafío es aprender a anclar tu elevada energía en el mundo práctico.",
    tip: "La meditación y el tiempo en la naturaleza son esenciales para calmar tu sistema nervioso. Confía en tu intuición por encima de todo. Encuentra una salida creativa para las visiones e inspiraciones que recibes. Rodéate de un entorno pacífico. No tengas miedo de ser diferente; tu propósito es traer una vibración única al mundo."
  },
  22: {
    meaning: "Un Número de Alma 22 revela un deseo profundo de construir algo de valor duradero que beneficie a la humanidad. Esta es una vibración maestra de 'Maestro Constructor'. Tu alma no solo sueña, sino que anhela convertir esos sueños en una realidad tangible. Te motiva la idea de dejar un legado. Combinas una visión idealista con una asombrosa capacidad práctica.",
    lightAndShadow: "En su vibración luminosa, tu alma tiene un potencial casi ilimitado para el logro. En sombra, la presión de este inmenso potencial puede ser abrumadora. Puedes sentir miedo al fracaso y optar por no intentar nada grande, o por el contrario, usar tu poder de manera egoísta o controladora.",
    tip: "Permítete soñar en grande. Luego, utiliza tu lado práctico para desglosar esa gran visión en pasos pequeños y manejables. Aprende sobre planificación y liderazgo. Colabora con otros que compartan tu visión. Mantén una conexión espiritual para asegurarte de que tus construcciones estén al servicio de un bien mayor."
  },
  33: {
    meaning: "Si tu Número de Alma es 33, tu deseo más profundo es el amor incondicional y la sanación. Esta es la vibración maestra del 'Maestro del Amor'. Tu alma anhela servir a la humanidad desde un lugar de profunda compasión y responsabilidad. Te motiva la idea de aliviar el sufrimiento y elevar la conciencia colectiva. Eres un sanador de almas por naturaleza.",
    lightAndShadow: "En luz, tu alma es un faro de amor, compasión y sabiduría. En sombra, la inmensa responsabilidad que sientes puede llevarte al sacrificio extremo y al síndrome del mártir. Puedes volverte demasiado perfeccionista en tu afán de 'salvar' a todos, descuidando por completo tus propias necesidades.",
    tip: "Tu prioridad número uno debe ser tu propio bienestar y amor propio. Establece límites muy claros para proteger tu energía. Utiliza tus dones creativos como una forma de expresar y canalizar tu energía sanadora. Practica el perdón, empezando por ti mismo. Tu misión es ser un canal de amor, no un receptáculo del dolor del mundo."
  }
};

export const PERSONALITY_NUMBER_MEANINGS: Record<number, Meaning> = {
  1: {
    meaning: "Tu Número de Personalidad 1 te presenta al mundo como un líder natural, una persona independiente y segura de sí misma. La gente percibe tu energía como la de alguien que sabe lo que quiere y no teme tomar la iniciativa. Proyectas una imagen de fuerza, coraje y originalidad. Los demás te ven como un pionero, alguien capaz de dirigir proyectos y tomar decisiones difíciles. Tu apariencia externa suele ser pulcra y con un estilo distintivo que refuerza tu individualidad. Eres la persona a la que otros acuden en busca de dirección y una visión clara.",
    lightAndShadow: "En luz, esta personalidad es carismática, magnética e inspiradora. La gente admira tu confianza y tu capacidad para mantenerte firme en tus convicciones. En sombra, puedes parecer arrogante, dominante o excesivamente egocéntrico. Tu necesidad de estar al mando puede ser percibida como autoritarismo, y tu independencia como una falta de interés en las opiniones ajenas. Puedes dar la impresión de ser inaccesible o de que no necesitas a nadie, lo que puede generar distancia.",
    tip: "Viste de una manera que exprese tu singularidad y te haga sentir poderoso. Asume roles de liderazgo, pero practica la escucha activa para demostrar que valoras a tu equipo. Aprende a pedir ayuda de vez en cuando; mostrar vulnerabilidad no te hace débil, sino más humano y accesible. Celebra los éxitos de los demás tanto como los tuyos. Esto equilibra tu energía de líder y te convierte en una figura inspiradora en lugar de una autoritaria."
  },
  2: {
    meaning: "Con un Número de Personalidad 2, proyectas una imagen de amabilidad, diplomacia y cooperación. Eres visto como una persona pacífica, considerada y un excelente oyente. La gente se siente cómoda a tu lado porque irradias una energía calmada y de apoyo. Te perciben como alguien en quien se puede confiar, un amigo leal y un socio colaborador. Tu estilo tiende a ser sutil y armonioso, evitando los extremos. Eres la persona a la que acuden para mediar en un conflicto o para recibir un consejo empático.",
    lightAndShadow: "En su aspecto luminoso, tu personalidad es encantadora, gentil y muy apreciada en los círculos sociales. La gente valora tu paciencia y tu capacidad para crear armonía. En sombra, puedes parecer indeciso, tímido o demasiado dependiente de la aprobación de los demás. Tu aversión al conflicto puede hacer que te perciban como alguien que no defiende sus propias ideas o que es fácilmente influenciable. Puedes dar la impresión de ser pasivo.",
    tip: "Desarrolla tu habilidad para la negociación y la mediación en entornos grupales. Viste con colores y estilos que te hagan sentir en paz y equilibrio. Aprende a expresar tus opiniones con amabilidad pero con firmeza, demostrando que la diplomacia no es sinónimo de debilidad. Trabaja en fortalecer tu confianza para que tu deseo de cooperar no se convierta en una necesidad de complacer. Participa en actividades de equipo donde tu rol de armonizador sea clave."
  },
  3: {
    meaning: "Tu Número de Personalidad 3 te muestra al mundo como alguien sociable, carismático y lleno de alegría de vivir. La gente te percibe como una persona optimista, creativa y con un gran sentido del humor. Proyectas una energía vibrante y juvenil que atrae a los demás. Eres el alma de la fiesta, el que cuenta las mejores historias y el que siempre tiene una palabra de aliento. Tu estilo suele ser colorido y expresivo, reflejando tu naturaleza artística. Los demás te ven como alguien inspirador.",
    lightAndShadow: "En luz, tu personalidad es magnética, divertida y edificante. La gente se siente atraída por tu entusiasmo. En sombra, puedes ser percibido como superficial, disperso o dramático. Tu necesidad de ser el centro de atención puede resultar agotadora para algunos, y tu optimismo puede parecer una negación de los problemas serios. Puedes tener la reputación de ser alguien que habla mucho pero concreta poco.",
    tip: "Utiliza tu don de la comunicación para inspirar y motivar a otros. Viste de una manera que te haga sentir creativo y alegre. Elige un pasatiempo artístico y compártelo con el mundo. Practica enfocar tu energía terminando los proyectos que empiezas. Aprende a equilibrar tu sociabilidad con momentos de introspección para conectar con tu yo más profundo. Esto hará que tu alegría sea más auténtica."
  },
  4: {
    meaning: "Un Número de Personalidad 4 te presenta como una persona sólida, confiable y trabajadora. La gente te ve como alguien disciplinado, organizado y con los pies en la tierra. Proyectas una imagen de estabilidad y seguridad; eres la roca en la que otros pueden apoyarse. Tu estilo tiende a ser práctico, conservador y funcional. Los demás admiran tu perseverancia y tu enfoque metódico para resolver problemas. Eres percibido como alguien honesto y leal, que cumple su palabra.",
    lightAndShadow: "En su vibración luminosa, tu personalidad inspira confianza y respeto. Eres visto como alguien competente y responsable. En sombra, puedes parecer rígido, terco y demasiado serio. Tu aversión al riesgo y al cambio puede ser percibida como falta de imaginación o pesimismo. Puedes dar la impresión de ser un adicto al trabajo que no sabe cómo relajarse y disfrutar de la vida.",
    tip: "Asume roles que requieran planificación y organización. Viste de manera clásica y ordenada, lo que refuerza tu imagen de fiabilidad. Intencionalmente, agenda tiempo para el ocio y la diversión en tu calendario, tratándolo con la misma seriedad que el trabajo. Practica la flexibilidad probando nuevas rutinas o hobbies. Aprende a delegar tareas, confiando en que otros también pueden ser competentes."
  },
  5: {
    meaning: "Tu Número de Personalidad 5 te muestra al mundo como una persona aventurera, versátil y carismática. La gente te percibe como alguien lleno de energía, curioso y siempre listo para la próxima experiencia. Proyectas una imagen de libertad y adaptabilidad; pareces alguien que no se ata a nada. Tu estilo suele ser moderno, cambiante y un poco atrevido, reflejando tu naturaleza activa. Eres visto como alguien sociable, ingenioso y con una habilidad natural para conectar con todo tipo de personas.",
    lightAndShadow: "En luz, tu personalidad es magnética, emocionante y estimulante. La gente se siente atraída por tu espíritu libre. En sombra, puedes ser percibido como poco confiable, impulsivo o superficial. Tu constante necesidad de cambio puede hacer que parezcas incapaz de comprometerte, tanto en relaciones como en proyectos. Puedes dar la impresión de ser inquieto y de huir de la responsabilidad.",
    tip: "Elige un estilo de vida o carrera que te ofrezca variedad y desafíos constantes. Viste de una manera que te permita moverte con libertad. Aprende un nuevo idioma, viaja o toma clases sobre temas diversos para canalizar tu curiosidad. Practica el compromiso en un área de tu vida para demostrarte a ti mismo que puedes hacerlo. Aprende a encontrar la aventura en el día a día."
  },
  6: {
    meaning: "Con un Número de Personalidad 6, proyectas una imagen de calidez, responsabilidad y confianza. Eres visto como una persona nutridora, alguien a quien acudir en busca de consejo y consuelo. La gente percibe tu energía como la de un protector, un amigo leal y un pilar de la comunidad. Tu estilo tiende a ser armonioso, elegante y acogedor. Los demás te ven como alguien con un fuerte sentido de la justicia y un profundo amor por la familia y el hogar.",
    lightAndShadow: "En su aspecto luminoso, tu personalidad es amorosa, magnética y muy respetada. La gente confía en ti de forma natural. En sombra, puedes parecer enteometido, controlador o un 'sabelotodo'. Tu deseo de ayudar puede ser percibido como una necesidad de imponer tus estándares a los demás. Puedes dar la impresión de ser un perfeccionista que juzga a quienes no viven según tus ideales.",
    tip: "Crea un ambiente hogareño y laboral que sea estéticamente agradable. Ofrece tu ayuda y consejo, pero aprende a hacerlo solo cuando te lo pidan, respetando el libre albedrío de los demás. Viste con un estilo que refleje tu amor por la belleza y la calidad. Involúcrate en actividades comunitarias donde tu sentido de la responsabilidad pueda brillar. Practica el autocuidado para evitar el agotamiento."
  },
  7: {
    meaning: "Tu Número de Personalidad 7 te presenta al mundo como alguien sabio, introspectivo y un poco misterioso. La gente te percibe como una persona inteligente, analítica y con una profunda vida interior. Proyectas un aire de dignidad y reserva, lo que puede generar tanto respeto como intriga. No eres un libro abierto, y esto hace que los demás sientan que tienes un conocimiento oculto. Tu estilo suele ser sobrio y refinado. Eres visto como un experto en tu campo.",
    lightAndShadow: "En luz, tu personalidad es fascinante y emana una autoridad tranquila. La gente respeta tu inteligencia. En sombra, puedes parecer distante, frío o arrogante. Tu necesidad de soledad puede ser interpretada como esnobismo o desinterés por los demás. Puedes dar la impresión de ser demasiado crítico, escéptico o de vivir en tu propia torre de marfil.",
    tip: "No temas compartir tu conocimiento especializado a través de la escritura o la enseñanza. Viste con un estilo que sea elegante y atemporal. Dedica tiempo a la soledad para recargar, pero también haz el esfuerzo de iniciar conversaciones sobre temas que te apasionan. Esto te permitirá conectar con otros desde tu intelecto. Aprende a mostrar un poco más de tu lado vulnerable para parecer más accesible."
  },
  8: {
    meaning: "Un Número de Personalidad 8 te muestra al mundo como una persona poderosa, ambiciosa y competente. La gente te percibe como un líder natural, alguien con autoridad y un gran potencial para el éxito. Proyectas una imagen de control, eficiencia y confianza en el ámbito material. Tu estilo tiende a ser de alta calidad, profesional e impecable, reflejando tu gusto por el éxito. Los demás te ven como alguien con una gran visión para los negocios. Irradias una energía de poder y logro.",
    lightAndShadow: "En su vibración luminosa, tu personalidad es carismática e influyente. Eres visto como alguien capaz de lograr cualquier cosa que se proponga. En sombra, puedes parecer materialista, dominante e intimidante. Tu ambición puede ser percibida como una sed de poder desmedida, y tu eficiencia como impaciencia o falta de empatía. Puedes dar la impresión de ser una persona adicta al trabajo.",
    tip: "Asume roles de liderazgo y gestión. Viste para el éxito, con ropa de calidad que refleje tu ambición. Practica la generosidad, tanto con tu dinero como reconociendo el trabajo de tu equipo; esto demuestra un liderazgo magnánimo. Aprende a delegar para no sobrecargarte y para empoderar a otros. Asegúrate de equilibrar tu vida profesional con tus relaciones personales."
  },
  9: {
    meaning: "Tu Número de Personalidad 9 te presenta como una persona compasiva, carismática y con una visión global. La gente te percibe como un alma vieja, alguien sabio, tolerante y con un profundo interés por el bienestar de la humanidad. Proyectas una energía magnética y un aire de artista o filántropo. Tu estilo suele ser ecléctico y sin prejuicios. Los demás se sienten atraídos por tu idealismo y tu capacidad para comprender diferentes culturas. Eres visto como alguien generoso.",
    lightAndShadow: "En luz, tu personalidad es encantadora, inspiradora y universalmente atractiva. Eres visto como un líder humanitario. En sombra, puedes parecer dramático, emocionalmente distante o un soñador poco práctico. Tu idealismo puede ser percibido como una falta de realismo, y puedes dar la impresión de estar 'por encima' de las preocupaciones mundanas. A veces, puedes parecer un poco inaccesible.",
    tip: "Involúcrate en causas sociales o artísticas que te permitan expresar tu visión humanitaria. Viste de una manera que refleje tu espíritu creativo y universal. Viaja y aprende sobre diferentes culturas. Comparte tu sabiduría y compasión, pero aprende a establecer límites para no absorber el dolor del mundo. Practica el desapego. Tu carisma es un don; úsalo para inspirar cambios positivos."
  },
  11: {
    meaning: "Con un Número de Personalidad 11, proyectas una energía eléctrica, intuitiva e inspiradora. Esta es una vibración maestra, por lo que la gente te percibe como alguien especial, aunque no sepan explicar por qué. Irradias un carisma magnético y una sensibilidad casi psíquica. Eres visto como un soñador, un visionario o un artista con una conexión con algo superior. Tu presencia puede ser intensa y a menudo te encuentras en el centro de atención sin buscarlo.",
    lightAndShadow: "En luz, tu personalidad es la de un líder espiritual o un innovador inspirado. En sombra, la intensidad de esta energía puede hacerte parecer nervioso, ansioso o desconectado de la realidad. Puedes ser percibido como poco práctico, demasiado emocional o fanática en tus creencias. El desafío es mantener los pies en la tierra mientras canalizas tu elevada inspiración.",
    tip: "Confía en tu intuición y compártela. Viste de una manera que te haga sentir único. Encuentra una salida creativa para tu torrente de ideas. Practica técnicas de enraizamiento como caminar descalzo sobre la hierba o la meditación para manejar tu energía nerviosa. Tu propósito es inspirar, así que no tengas miedo de ser el visionario que eres, pero aprende a comunicar tus ideas de manera comprensible."
  },
  22: {
    meaning: "Un Número de Personalidad 22 te presenta al mundo como un 'Maestro Constructor'. Esta es la vibración de personalidad más poderosa. La gente te percibe como alguien con un potencial ilimitado, capaz de lograr hazañas extraordinarias. Proyectas una imagen de competencia, carisma y pragmatismo visionario. Eres visto como un líder capaz de tomar sueños idealistas y convertirlos en una realidad tangible. La gente confía en tu capacidad para manejar grandes proyectos.",
    lightAndShadow: "En su vibración luminosa, eres la personificación del 'poder con propósito'. Eres visto como un líder pragmático y exitoso. En sombra, la presión de este número puede hacerte parecer abrumado, o por el contrario, extremadamente controlador y manipulador. Si no estás a la altura de tu potencial, puedes ser percibido como alguien que habla mucho pero no actúa.",
    tip: "No temas asumir grandes responsabilidades. Viste de una manera que proyecte éxito y profesionalismo. Involúcrate en proyectos que tengan un impacto social a gran escala. Aprende a desglosar tus grandes visiones en pasos prácticos y manejables. Colabora y construye equipos sólidos; tu poder se magnifica cuando empoderas a otros. Mantén siempre una conexión con tu propósito más elevado."
  },
  33: {
    meaning: "Con un Número de Personalidad 33, proyectas la energía del 'Maestro del Amor'. La gente te percibe como una persona excepcionalmente compasiva, sanadora y responsable. Irradias una luz de amor incondicional y sabiduría. Eres visto como un consejero, un maestro o un guía espiritual, incluso si no ocupas formalmente esos roles. Tu presencia es calmante y elevadora, y la gente se siente naturalmente atraída hacia ti en busca de consuelo.",
    lightAndShadow: "En luz, tu personalidad es la de un sanador y un maestro del corazón. Eres un faro de amor y compasión. En sombra, la inmensa carga emocional de este número puede hacerte parecer un mártir, alguien que se sacrifica en exceso y se olvida de sí mismo. Puedes ser percibido como perfeccionista o demasiado idealista en tus expectativas sobre los demás.",
    tip: "Tu autocuidado es primordial. Establece límites muy claros para proteger tu energía. Utiliza tus talentos creativos para expresar y compartir tu mensaje de amor. Enfócate en enseñar con el ejemplo, viviendo una vida de alegría y compasión. No intentes 'salvar' a todos; en su lugar, empodéralos para que se salven a sí mismos. Tu simple presencia, cuando está vibrando en amor propio, es tu mayor herramienta."
  }
};

export const EXPRESSION_NUMBER_MEANINGS: Record<number, Meaning> = {
  1: {
    meaning: "Tu Número de Expresión 1 revela que tu misión de vida es desarrollar y expresar tu individualidad, liderazgo y originalidad. Estás aquí para ser un pionero, para iniciar proyectos y abrir nuevos caminos con tus ideas innovadoras. Tus talentos innatos son la independencia, la determinación y una fuerte voluntad. Tienes la capacidad de dirigir y motivar a otros, y tu propósito se cumple cuando confías en tu propia voz y actúas con coraje para manifestar tu visión única en el mundo.",
    lightAndShadow: "En luz, eres un líder nato, creativo y ambicioso, capaz de alcanzar grandes logros por ti mismo. Inspiras a otros con tu confianza y determinación. En sombra, esta energía puede manifestarse como arrogancia, egoísmo o una tendencia a ser demasiado dominante. Puedes tener dificultades para trabajar en equipo o para aceptar consejos, creyendo que tu manera es la única correcta. El desafío es liderar de forma inclusiva.",
    tip: "Asume roles de liderazgo en tu vida profesional o personal. No temas emprender proyectos en solitario que te apasionen. Practica la autoafirmación y trabaja en fortalecer tu confianza. Al mismo tiempo, cultiva la habilidad de escuchar y valorar las contribuciones de los demás. Aprende a delegar y a confiar, entendiendo que el verdadero liderazgo empodera a todo el equipo, no solo al líder."
  },
  2: {
    meaning: "Con un Número de Expresión 2, tu misión es traer armonía, cooperación y diplomacia al mundo. Tus talentos naturales residen en tu sensibilidad, paciencia y tu increíble capacidad para ver ambos lados de cualquier situación. Estás aquí para ser un pacificador, un mediador y un excelente socio o compañero de equipo. Tu propósito se realiza cuando usas tu empatía para unir a las personas, crear relaciones equilibradas y fomentar la colaboración. La belleza, el amor y la conexión son fundamentales para tu camino.",
    lightAndShadow: "En su vibración luminosa, eres un diplomático excepcional, un amigo leal y un apoyo incondicional. Tu intuición es una guía poderosa. En sombra, puedes volverte demasiado dependiente de la aprobación de los demás, indeciso y con miedo al conflicto. Tu sensibilidad puede convertirse en hipersensibilidad, haciéndote vulnerable a las críticas. El desafío es mantener tu naturaleza pacificadora sin sacrificar tus propias necesidades.",
    tip: "Desarrolla tus habilidades en negociación, consejería o cualquier campo que requiera diplomacia. Trabaja en equipo y busca roles donde puedas ser el 'pegamento' que une al grupo. Cultiva relaciones basadas en el respeto mutuo. Aprende a establecer límites saludables y a expresar tus sentimientos de manera constructiva. Confía en tu intuición y úsala para guiar tus decisiones y tus interacciones."
  },
  3: {
    meaning: "Tu Número de Expresión 3 indica que tu misión de vida es expresar alegría, creatividad y comunicación. Estás aquí para inspirar y elevar a otros a través de tus palabras, tu arte y tu optimismo. Tus talentos innatos incluyen la imaginación, la sociabilidad y un maravilloso sentido del humor. Tu propósito se cumple cuando utilizas tu voz para compartir tu visión única del mundo, trayendo belleza y entusiasmo a tu entorno. Eres un artista del alma, y tu vida es tu lienzo.",
    lightAndShadow: "En luz, eres un comunicador carismático, un artista talentoso y una fuente de alegría para quienes te rodean. Tu creatividad no tiene límites. En sombra, esta energía puede volverse dispersa y superficial. Puedes empezar muchos proyectos sin terminar ninguno, o usar tu don para la comunicación de manera frívola (chismes, exageración). El desafío es enfocar tu energía creativa y comunicar con profundidad y autenticidad.",
    tip: "Elige una disciplina artística o un canal de comunicación y dedícale tiempo y esfuerzo. Ya sea escribiendo, pintando, cantando o hablando en público, comprométete a desarrollar tu talento. Practica la comunicación desde el corazón. Rodéate de belleza e inspiración. No temas expresar tus emociones más profundas; tu vulnerabilidad es una fuente de conexión y poder creativo."
  },
  4: {
    meaning: "Un Número de Expresión 4 revela que tu misión es construir algo de valor duradero a través de la disciplina, el trabajo duro y la organización. Estás aquí para traer orden y estabilidad al mundo. Tus talentos naturales son la perseverancia, la honestidad y una increíble capacidad para la planificación y la ejecución. Tu propósito se realiza cuando aplicas tu enfoque metódico para crear sistemas, estructuras o productos que sean sólidos y fiables. Eres el pilar de la sociedad.",
    lightAndShadow: "En su vibración luminosa, eres la persona más confiable y trabajadora que se pueda encontrar. Tu dedicación te permite alcanzar grandes logros. En sombra, puedes volverte rígido, terco y resistente al cambio. Tu enfoque en el detalle puede hacerte perder la visión general, y puedes caer en la rutina y el exceso de trabajo, olvidando disfrutar de la vida. El desafío es combinar tu disciplina con una mente abierta y flexible.",
    tip: "Involúcrate en proyectos a largo plazo que requieran planificación y dedicación. Desarrolla un sistema de organización que funcione para ti. Aprende a equilibrar tu vida laboral con el descanso y el ocio. Practica la flexibilidad intentando nuevas formas de hacer las cosas. Confía en el proceso y celebra tus logros paso a paso. Tu legado se construye ladrillo a ladrillo, con paciencia y esfuerzo."
  },
  5: {
    meaning: "Tu Número de Expresión 5 indica que tu misión es experimentar la vida, abrazar el cambio y promover la libertad. Estás aquí para ser un catalizador, para romper con lo convencional y para usar tus múltiples talentos de manera versátil. Tus dones innatos son la adaptabilidad, la curiosidad y una habilidad natural para comunicarte y conectar con todo tipo de personas. Tu propósito se cumple cuando vives sin miedo, exploras el mundo y usas tus experiencias para inspirar a otros a vivir más libremente.",
    lightAndShadow: "En luz, eres magnético, aventurero y un maestro de la adaptación. Aprendes rápido y te desenvuelves bien en cualquier entorno. En sombra, esta energía puede manifestarse como inconsistencia, irresponsabilidad y una tendencia a los excesos. Tu aversión a la rutina puede llevarte a huir del compromiso y a dejar las cosas a medias. El desafío es encontrar la libertad dentro de la disciplina.",
    tip: "Elige una carrera o un estilo de vida que te ofrezca variedad y la oportunidad de viajar o aprender constantemente. Desarrolla tus habilidades de comunicación. Practica el compromiso en un área de tu vida para demostrarte que puedes tener raíces y alas al mismo tiempo. Usa tu energía para luchar por causas sociales que promuevan la libertad y el progreso. Conecta con la naturaleza para enraizar tu energía inquieteta."
  },
  6: {
    meaning: "Con un Número de Expresión 6, tu misión de vida es servir, nutrir y crear armonía, especialmente en el ámbito del hogar, la familia y la comunidad. Estás aquí para ser un consejero, un sanador y un protector. Tus talentos naturales incluyen la compasión, la responsabilidad y un fuerte sentido de la justicia. Tu propósito se realiza cuando creas belleza y equilibrio en tu entorno y asumes la responsabilidad de cuidar a los demás con amor y dedicación. Eres el corazón de cualquier grupo.",
    lightAndShadow: "En su vibración luminosa, eres una persona amorosa, protectora y confiable, un verdadero pilar para tus seres queridos. Tienes un don para la sanación y la enseñanza. En sombra, puedes volverte controlador, entrometido y perfeccionista. Tu deseo de ayudar puede llevarte a asumir cargas que no te corresponden, convirtiéndote en un mártir. El desafío es cuidar a los demás sin descuidarte a ti mismo y sin imponer tu visión.",
    tip: "Involúcrate en profesiones de servicio como la enseñanza, la terapia o el trabajo comunitario. Crea un hogar que sea un refugio de paz y belleza. Aprende a establecer límites saludables, ofreciendo tu ayuda sin sacrificar tu propio bienestar. Practica el autocuidado como una prioridad. Expresa tu creatividad a través del arte, la música o la decoración para canalizar tu amor por la armonía."
  },
  7: {
    meaning: "Tu Número de Expresión 7 revela que tu misión es buscar, analizar y compartir la sabiduría y la verdad. Estás aquí para ser un pensador profundo, un investigador y un puente entre el mundo científico y el espiritual. Tus talentos innatos son una mente analítica, una poderosa intuición y una capacidad para la introspección. Tu propósito se cumple cuando te dedicas a estudiar los misterios de la vida, confías en tu guía interior y compartes tus descubrimientos para iluminar a otros.",
    lightAndShadow: "En luz, eres un especialista brillante, un sabio intuitivo y un buscador de la verdad con una gran integridad. Tu mente es tu mayor herramienta. En sombra, puedes tender al aislamiento, al escepticismo y a la frialdad emocional. Tu perfeccionismo puede llevarte a la procrastinación, y tu mente analítica puede desconectarte de tu corazón. El desafío es equilibrar tu intelecto con tus emociones y compartir tu sabiduría con el mundo.",
    tip: "Elige un campo de estudio que te apasione y conviértete en un experto. Dedica tiempo a la soledad, la meditación y la reflexión para conectar con tu sabiduría interior. Confía en tu intuición tanto como en tu lógica. Pasa tiempo en la naturaleza para calmar tu mente. Encuentra formas de compartir tu conocimiento, ya sea escribiendo, enseñando o a través de conversaciones profundas."
  },
  8: {
    meaning: "Un Número de Expresión 8 indica que tu misión de vida es alcanzar la maestría en el mundo material, aprendiendo a manejar el poder, el dinero y la autoridad con sabiduría e integridad. Estás aquí para ser un líder, un ejecutivo y un manifestador de grandes proyectos. Tus talentos naturales son la ambición, la organización y una increíble capacidad para la ejecución. Tu propósito se realiza cuando usas tu fuerza y tu visión para construir algo de valor duradero y para empoderar a otros.",
    lightAndShadow: "En su vibración luminosa, eres un líder poderoso y exitoso, capaz de lograr un gran impacto en el mundo. Eres justo y eficiente. En sombra, esta energía puede manifestarse como autoritarismo, materialismo y una obsesión por el control. Puedes volverte adiscto al trabajo y descuidar tus relaciones personales. El desafío es equilibrar tu ambición material con la generosidad y la integridad espiritual.",
    tip: "Asume roles de liderazgo en los negocios o en tu comunidad. Aprende sobre finanzas e inversiones. Establece metas ambiciosas y crea planes estratégicos para alcanzarlas. Practica la generosidad y la filantropía. Asegúrate de que tus objetivos empresariales tengan un propósito más allá del beneficio económico. Aprende a delegar y a confiar en tu equipo, usando tu poder para empoderar a otros."
  },
  9: {
    meaning: "Tu Número de Expresión 9 revela que tu misión es el servicio desinteresado, la compasión y la sabiduría universal. Estás aquí para ser un humanitario, un artista y un maestro, utilizando tus talentos para inspirar y elevar a la humanidad. Tus dones innatos son una profunda empatía, una gran creatividad y una visión global. Tu propósito se cumple cuando vives desde el corazón, perdonas, sueltas el pasado y trabajas por un mundo mejor. Eres un alma vieja con mucho que ofrecer.",
    lightAndShadow: "En luz, eres un ser compasivo, carismático y generoso, capaz de inspirar a multitudes. Tu amor es incondicional. En sombra, puedes sentirte abrumado por el sufrimiento del mundo, lo que te lleva a la melancolía o al idealismo poco práctico. Puedes tener dificultades para recibir y para poner límites, sacrificándose hasta el punto del agotamiento y el resentimiento.",
    tip: "Involúcrate en causas humanitarias, artísticas o espirituales. Viaja y expande tu visión del mundo. Practica el perdón y el desapego. Utiliza tus talentos creativos para transmitir mensajes de esperanza y unidad. Aprende a establecer límites emocionales saludables para no agotarte. Sé un ejemplo vivo de compasión y tolerancia en tu día a día."
  },
  11: {
    meaning: "Con un Número de Expresión 11, tu misión de vida es ser un canal de inspiración y revelación espiritual. Esta es una vibración maestra que te dota de una intuición extraordinaria y una conexión directa con los planos superiores. Estás aquí para iluminar, para ser un visionario y para elevar la conciencia de la humanidad. Tus talentos son la clarividencia, la creatividad y un carisma magnético. Tu propósito se cumple cuando confías en tu guía interior y usas tu sensibilidad para inspirar a otros.",
    lightAndShadow: "En luz, eres un líder espiritual, un artista inspirado y un sanador. Tu presencia es eléctrica y transformadora. En sombra, la intensidad de esta energía puede causar una gran tensión nerviosa, ansiedad y confusión. Puedes sentirte desconectado de la realidad o abrumado por tu propia sensibilidad. El desafío es aprender a enraizar tu energía y a vivir en el mundo práctico sin perder tu conexión espiritual.",
    tip: "La meditación y las prácticas de enraizamiento (como pasar tiempo en la naturaleza) son esenciales para ti. Confía en tu intuición como tu principal herramienta. Encuentra una salida creativa para canalizar el torrente de inspiración que recibes. Rodéate de un entorno armonioso. No temas ser diferente; tu misión es traer una nueva visión al mundo."
  },
  22: {
    meaning: "Tu Número de Expresión 22 es la vibración del 'Maestro Constructor'. Tu misión es tomar sueños e ideales elevados y convertirlos en una realidad tangible que beneficie a la humanidad a gran escala. Estás aquí para ser un líder pragmático y visionario. Combinas la intuición del 11 con la disciplina del 4. Tus talentos son la planificación estratégica, la gestión de recursos y una capacidad casi ilimitada para la manifestación. Tu propósito es dejar un legado duradero.",
    lightAndShadow: "En su vibración luminosa, eres capaz de lograr hazañas extraordinarias que impactan positivamente en la sociedad. Eres un líder poderoso y práctico. En sombra, la presión de este potencial puede ser abrumadora, llevándote a evitar tus responsabilidades o, por el contrario, a usar tu poder de manera egoísta y controladora. El desafío es mantener tus grandes ambiciones alineadas con un propósito de servicio.",
    tip: "Piensa en grande. No limites tus sueños. Aprende sobre gestión, finanzas y liderazgo. Desglosa tus grandes visiones en pasos prácticos y alcanzables. Colabora con otros para manifestar tus proyectos; no tienes que hacerlo todo solo. Mantén una conexión espiritual para asegurarte de que tus construcciones sirvan a un bien mayor. Eres el arquitecto de un nuevo mundo."
  },
  33: {
    meaning: "Un Número de Expresión 33 te designa como el 'Maestro del Amor Sanador'. Tu misión de vida es el servicio desinteresado y la sanación a través de la compasión y la responsabilidad. Estás aquí para ser un faro de amor incondicional, para enseñar y para elevar la vibración de quienes te rodean. Combinas la expresión creativa del 3 con la energía nutridora del 6 a un nivel superior. Tu propósito se cumple cuando te conviertes en un canal de sanación y guía para la humanidad.",
    lightAndShadow: "En luz, eres un maestro, un sanador y un consejero excepcional. Tu presencia es calmante y elevadora. Tu amor y compasión pueden sanar heridas profundas. En sombra, la inmensa responsabilidad que sientes puede llevarte al sacrificio extremo y al síndrome del mártir. Puedes volverte perfeccionista y crítico, tanto contigo mismo como con los demás. El desafío es servir desde la alegría y la plenitud, no desde la obligación.",
    tip: "Tu autocuidado y amor propio son la base de tu misión. No puedes dar desde una vasija vacía. Establece límites muy claros para proteger tu energía. Utiliza tus talentos creativos (arte, música, enseñanza) para expresar tu mensaje de amor. Practica el perdón y la compasión, empezando por ti. Concéntrate en enseñar con el ejemplo, viviendo una vida de alegría y responsabilidad equilibrada."
  }
};

export const STRENGTH_NUMBER_MEANINGS: Record<number, Meaning> = {
  1: {
    meaning: "Tu Número de Fuerza 1 te otorga el don innato del liderazgo y la independencia. Esta es tu herramienta secreta para superar los momentos más difíciles. Cuando te enfrentas a un desafío, tu capacidad para tomar la iniciativa, confiar en tu propio juicio y actuar con coraje es tu mayor activo. Esta fuerza te impulsa a ser autosuficiente y a encontrar soluciones originales donde otros ven obstáculos. Es la energía del pionero que reside en ti, siempre lista para abrir un nuevo camino cuando los antiguos se cierran.",
    lightAndShadow: "En su vibración de luz, esta fuerza te convierte en una persona decidida, innovadora y capaz de liderar tu propia vida con una confianza inquebrantable. Te permite levantarte rápidamente de las caídas. En sombra, si no confías en este don, puedes volverte dependiente de la opinión ajena o sentirte paralizado por la indecisión. También puede manifestarse como una terquedad que te impide pedir ayuda cuando es necesario, creyendo erróneamente que la fuerza es sinónimo de no necesitar a nadie.",
    tip: "En momentos de duda, tómate un momento a solas para conectar con tu propia voz interior, lejos del ruido externo. Confía en esa primera corazonada. Ponte pequeños desafíos que te obliguen a actuar por tu cuenta para fortalecer este 'músculo' de la independencia. Recuerda que tu fuerza no es para aislarte, sino para guiarte. Lidera tu vida primero, y verás cómo esa seguridad se convierte en un faro para ti y para los demás."
  },
  2: {
    meaning: "Tu Número de Fuerza 2 te confiere el don de la diplomacia, la intuición y la cooperación. En los momentos de mayor tensión o conflicto, tu habilidad natural para crear armonía y entender diferentes perspectivas es tu superpoder. Esta fuerza te permite navegar situaciones complejas con gracia y paciencia, construyendo puentes en lugar de muros. Tu intuición es una brújula infalible que te guía hacia las soluciones más pacíficas y beneficiosas para todos los involucrados. Eres un pacificador nato.",
    lightAndShadow: "En luz, esta fuerza te convierte en un mediador excepcional, un socio confiable y una persona con una profunda inteligencia emocional. Sabes instintivamente qué decir y cómo actuar para calmar las aguas. En sombra, si no la usas conscientemente, puedes caer en la evasión del conflicto a toda coda, sacrificando tus propias necesidades. Puedes volverte demasiado sensible a las energías de los demás, perdiendo tu propio centro. El desafío es usar tu don para unir, no para desaparecer.",
    tip: "Cuando te enfrentes a un conflicto, respira hondo y activa tu rol de observador imparcial antes de reaccionar. Confía en lo que sientes sobre una situación, incluso si no puedes explicarlo lógicamente. Ofrece tu consejo para mediar entre amigos o colegas. Practica el equilibrio: apoya a los demás, pero asegúrate también de expresar tus propias necesidades con calma y claridad. Tu gentileza es tu mayor fortaleza."
  },
  3: {
    meaning: "Tu Número de Fuerza 3 te brinda el don de la creatividad, la comunicación y el optimismo. Cuando la vida se pone gris o te sientes estancado, tu capacidad para encontrar una salida creativa y expresar tus sentimientos es tu salvavidas. Esta fuerza te permite transformar el dolor en arte, la confusión en claridad a través de la palabra y la desesperanza en una nueva visión optimista. Tienes una habilidad innata para conectar con los demás y levantar el ánimo, tanto el tuyo como el de tu entorno, a través de la alegría y la expresión.",
    lightAndShadow: "En su vibración luminosa, esta fuerza te convierte en una persona resiliente que siempre encuentra una razón para sonreír y seguir adelante. Eres ingenioso y carismático. En sombra, si ignoras este don, puedes reprimir tus emociones y caer en la melancolía. Puedes usar la comunicación de manera superficial para evadir problemas profundos o dispersar tu energía en demasiadas ideas sin concretar ninguna. El desafío es canalizar tu creatividad con un propósito.",
    tip: "En momentos difíciles, busca una salida creativa: escribe lo que sientes, dibuja, canta, baila. No tiene que ser perfecto, solo tiene que ser expresivo. Habla con un amigo de confianza y pon tus sentimientos en palabras. Rodéate de belleza y colores para estimular tu energía. Recuerda que tu optimismo no es negar lo malo, sino tu habilidad para encontrar la luz incluso en la oscuridad. Úsalo como tu linterna."
  },
  4: {
    meaning: "Tu Número de Fuerza 4 te otorga el don de la disciplina, la perseverancia y la planificación. Cuando el caos amenaza con desbordarte, tu capacidad innata para crear orden, establecer un plan y trabajar en él paso a paso es tu ancla. Esta fuerza te da una resistencia increíble para superar los desafíos a largo plazo. No te rindes fácilmente. Eres capaz de construir soluciones prácticas y duraderas donde otros solo ven desorden. Tu fortaleza reside en tu enfoque metódico y tu inquebrantable dedicación.",
    lightAndShadow: "En luz, esta fuerza te convierte en una persona increíblemente confiable y resiliente, capaz de construir una vida segura y estable incluso en tiempos de incertidumbre. Eres la roca para ti y para los demás. En sombra, si te aferras demasiado a ella, puedes volverte rígido e inflexible, temeroso de cualquier cambio que altere tus planes. Puedes caer en el exceso de trabajo como una forma de controlar la ansiedad. El desafío es ser estructurado sin ser prisionero de tu propia estructura.",
    tip: "Cuando te sientas abrumado, coge papel y lápiz. Haz una lista de tareas y divídela en pasos pequeños y manejables. Crear un plan de acción calmará tu sistema nervioso. Establece rutinas diarias que te den una sensación de seguridad y control. Confía en tu capacidad para el trabajo duro, pero recuerda también programar descansos. Tu disciplina es tu superpoder; úsala para construir la vida que deseas, no una jaula."
  },
  5: {
    meaning: "Tu Número de Fuerza 5 te confiere el don de la adaptabilidad, la versatilidad y el ingenio. Cuando te enfrentas a cambios inesperados o a crisis, tu habilidad para pensar con rapidez, encontrar soluciones no convencionales y ajustarte a las nuevas circunstancias es tu mayor talento. No te rompes, te flexionas. Esta fuerza te permite ver las oportunidades ocultas en el caos y te da el coraje para soltar lo viejo y abrazar lo nuevo. Eres un maestro de la reinvención y un agente de cambio por naturaleza.",
    lightAndShadow: "En su vibración luminosa, esta fuerza te hace increíblemente resiliente, ingenioso y capaz de prosperar en cualquier entorno. Eres un solucionador de problemas nato. En sombra, si no se canaliza, esta energía puede manifestarse como inquietud, inconsistencia y una tendencia a huir de los problemas en lugar de enfrentarlos. Puedes tener dificultades para comprometerte por miedo a sentirte atrapado. El desafío es usar tu adaptabilidad para navegar la vida, no para escapar de ella.",
    tip: "Ante un problema, en lugar de preguntarte '¿Por qué a mí?', pregúntate '¿Qué puedo aprender de esto?' y '¿Cuál es la solución más creativa?'. Acepta el cambio como tu aliado. Practica actividades que requieran adaptabilidad, como los deportes de improvisación o los viajes. Aprende a diferenciar entre la libertad constructiva y el escapismo. Tu capacidad para adaptarte es tu red de seguridad; confía en que siempre caerás de pie."
  },
  6: {
    meaning: "Tu Número de Fuerza 6 te otorga el don de la sanación, la responsabilidad y la capacidad de crear armonía. En los momentos de crisis emocional, ya sea tuya o de otros, tu habilidad innata para ofrecer consuelo, consejo sabio y un espacio seguro es tu mayor fortaleza. Eres un sanador natural, capaz de ver la belleza incluso en las situaciones más difíciles y de restaurar el equilibrio. Esta fuerza te impulsa a asumir la responsabilidad y a encontrar soluciones que beneficien a todos, especialmente a tu círculo más cercano.",
    lightAndShadow: "En luz, esta fuerza te convierte en un pilar de amor y apoyo para tu comunidad. Eres un consejero nato y un pacificador. En sombra, puedes tender a asumir las cargas de los demás hasta el punto del agotamiento, convirtiéndote en un mártir. Tu deseo de 'arreglar' las cosas puede volverse controlador. El desafío es aprender a cuidar de los demás sin perderte a ti mismo en el proceso.",
    tip: "Confía en tu capacidad para dar consejos, pero ofrécelos solo cuando te los pidan. Crea un ambiente armonioso en tu hogar, ya que es tu santuario para recargar energías. Aprende a ponerte a ti mismo en primer lugar en tu lista de responsabilidades; practica el autocuidado de manera consciente. Recuerda que no puedes servir desde una vasija vacía. Tu capacidad para amar y sanar es un regalo; úsalo sabiamente, empezando por ti."
  },
  7: {
    meaning: "Tu Número de Fuerza 7 te confiere el don de la introspección, el análisis y la conexión con una sabiduría más profunda. Cuando te enfrentas a la confusión o la incertidumbre, tu capacidad para retirarte, analizar la situación con una mente aguda y conectar con tu intuición es tu herramienta más poderosa. No te dejas llevar por el pánico; buscas la verdad oculta bajo la superficie. Esta fuerza te permite encontrar claridad en la soledad y confiar en una guía interna que trasciende la lógica convencional.",
    lightAndShadow: "En su vibración luminosa, esta fuerza te convierte en un estratega brillante y una persona con una profunda paz interior. Tomas decisiones sabias basadas en una mezcla de análisis e intuición. En sombra, si no confías en este don, puedes caer en el pensamiento excesivo y la ansiedad. Puedes aislarte del mundo por miedo o desconfianza. El desafío es equilibrar tu necesidad de soledad con la conexión humana y confiar en lo que sabes en tu interior.",
    tip: "Cuando te sientas perdido, date permiso para estar a solas. Medita, camina por la naturaleza o simplemente siéntate en silencio. Las respuestas que buscas no están fuera, sino dentro de ti. Lleva un diario para ayudarte a procesar tus pensamientos y a conectar con tu intuición. Confía en tus 'corazonadas'. Estudia temas que te interesen profundamente para nutrir tu mente analítica. Tu sabiduría interior es tu faro en la tormenta."
  },
  8: {
    meaning: "Tu Número de Fuerza 8 te otorga el don del poder personal, la resiliencia y la capacidad de manifestación. En los momentos de mayor desafío, especialmente en el ámbito material o profesional, tu habilidad innata para tomar el control, establecer una estrategia y ejecutarla con autoridad es tu mayor fortaleza. Eres increíblemente resiliente y tienes la capacidad de transformar los fracasos en oportunidades. Esta fuerza te impulsa a ser ambicioso y a construir algo de gran valor. Eres un líder nato con un poder de manifestación excepcional.",
    lightAndShadow: "En luz, esta fuerza te convierte en una persona exitosa, influyente y capaz de superar cualquier adversidad. Eres un maestro de la materialización. En sombra, puedes volverte demasiado controlador, impaciente o materialista, creyendo que el poder lo es todo. Puedes tener miedo a la vulnerabilidad y ocultar tus emociones detrás de una fachada de dureza. El desafío es ejercer tu poder con integridad y compasión.",
    tip: "Ante un revés, en lugar de sentirte una víctima, activa tu 'modo ejecutivo'. Analiza la situación, crea un nuevo plan y ponte en acción. Asume la responsabilidad de tu vida financiera y profesional. Aprende a ver los desafíos como oportunidades para demostrar tu fuerza. Practica la generosidad; compartir tu éxito amplifica tu poder. Recuerda que tu verdadero poder no es controlar a los demás, sino ser el maestro de tu propio destino."
  },
  9: {
    meaning: "Tu Número de Fuerza 9 te confiere el don de la compasión, la sabiduría y una perspectiva universal. Cuando te enfrentas al dolor, la pérdida o la injusticia, tu capacidad innata para ver la situación desde un punto de vista más elevado y para conectar con un amor compasivo es tu mayor fortaleza. Esta fuerza te permite perdonar, soltar y encontrar un significado más profundo en las pruebas de la vida. Eres un alma vieja, y tu sabiduría te ayuda a navegar las dificultades con una gracia y una comprensión que inspiran a los demás.",
    lightAndShadow: "En su vibración luminosa, esta fuerza te convierte en una persona increíblemente resiliente a nivel emocional. Eres tolerante, sabio y un faro de esperanza. En sombra, puedes sentirte abrumado por el suffering del mundo, absorbiendo el dolor ajeno como si fuera tuyo. Puedes tener dificultades para soltar el pasado o para poner límites, sacrificándote en exceso. El desafío es ser compasivo sin perderte a ti mismo.",
    tip: "En momentos de dificultad, intenta ver la situación desde una perspectiva más amplia, como si fueras un observador sabio. Pregúntate: '¿Qué lección hay aquí para mi alma?'. Practica el perdón, tanto hacia los demás como hacia ti mismo; es tu herramienta de liberación más poderosa. Involúcrate en actividades que te permitan canalizar tu compasión de manera saludable, como el voluntariado. Recuerda que para poder ayudar al mundo, primero debes proteger tu propia paz interior."
  },
  11: {
    meaning: "Tu Número de Fuerza 11, una vibración maestra, te otorga el don de la intuición elevada e la inspiración divina. En los momentos de mayor confusión o crisis, tu capacidad para recibir 'descargas' de información y guía de planos superiores es tu superpoder. Eres un canal. Esta fuerza te permite ver la verdad oculta detrás de las apariencias y encontrar soluciones que desafían la lógica convencional. Tu conexión con lo espiritual es tu ancla y tu faro, iluminando el camino cuando todo parece oscuro.",
    lightAndShadow: "En luz, esta fuerza te convierte en un visionario, un sanador y un guía inspirado. Confiar en tu intuición te lleva a tomar decisiones milagrosas. En sombra, la intensidad de esta energía puede generar una gran ansiedad y tensión nerviosa. Si dudas de tu don, puedes sentirte perdido y desconectado, o abrumado por energías que no comprendes. El desafío es confiar en tu guía interna y aprender a enraizar tu energía.",
    tip: "La meditación no es una opción, es una necesidad para ti. Es la forma de limpiar tu canal y escuchar tu guía con claridad. Cuando te enfrentes a un problema, pide una señal y luego presta atención a tus sueños, sincronicidades y corazonadas. Confía en esa voz interior, incluso si no tiene sentido para los demás. Pasa tiempo en la naturaleza para descargar el exceso de energía. Tu intuición es tu don más preciado; hónrala y síguela."
  },
  22: {
    meaning: "Tu Número de Fuerza 22, una vibración maestra, te confiere el don de la manifestación a gran escala. Eres el 'Maestro Constructor'. Cuando te enfrentas a desafíos que parecen insuperables, tu habilidad innata para combinar una visión idealista con una acción práctica y disciplinada es tu mayor activo. Tienes la capacidad de tomar el caos y convertirlo en un sistema ordenado, de tomar un sueño y construirlo en la realidad. Esta fuerza te da la resistencia y la visión para liderar proyectos que pueden cambiar el mundo.",
    lightAndShadow: "En su vibración luminosa, esta fuerza te permite lograr hazañas extraordinarias. Eres un líder pragmático y visionario. En sombra, la inmensa presión de este don puede hacer que temas a tu propio poder y optes por no usarlo, viviendo una vida por debajo de tu potencial. O, por el contrario, puedes volverte extremadamente controlador y obstinado. El desafío es aceptar la magnitud de tu poder y usarlo para un bien mayor.",
    tip: "No tengas miedo de tus grandes sueños. Escríbelos. Luego, usa tu lado práctico para desglosarlos en un plan de acción detallado. Ante un problema, en lugar de sentirte abrumado, ponte tu 'casco de constructor' y empieza a trabajar en la solución, paso a paso. Aprende a colaborar y a inspirar a otros para que te ayuden a construir tu visión. Recuerda que tienes la capacidad de convertir los sueños en realidad; confía en ese poder."
  },
  33: {
    meaning: "Tu Número de Fuerza 33, la vibración maestra más elevada, te otorga el don de la sanación a través del amor incondicional y el servicio compasivo. En los momentos de mayor dolor, división o desesperanza, tu capacidad innata para irradiar amor, comprensión y alegría es tu fuerza más poderosa. Eres un sanador del alma. Esta fuerza te permite elevar la vibración de cualquier situación o persona simplemente con tu presencia. Tu don es enseñar con el ejemplo, mostrando al mundo el poder transformador del amor.",
    lightAndShadow: "En luz, eres un faro de esperanza y un catalizador para la sanación emocional y espiritual. Tu compasión es tu superpoder. En sombra, la intensidad de esta energía puede llevarte a asumir el sufrimiento del mundo como propio, cayendo en el syndrome del mártir. Puedes descuidar tus propias necesidades hasta el punto del agotamiento. El desafío es aprender a ser un canal de amor, no un receptáculo del dolor.",
    tip: "Tu prioridad absoluta debe ser tu propio bienestar emocional y tu alegría. Haz cosas que te hagan feliz. Establece límites energéticos muy claros. Cuando te enfrentes a una situación dolorosa, en lugar de sumergirte en el dolor, concéntrate en enviar amor y luz a la situación desde un lugar de plenitud. Utiliza tus talentos creativos para expresar y compartir tu energía sanadora. Recuerda que tu ejemplo de vida gozosa es tu mayor servicio al mundo."
  }
};

export const PERSONAL_YEAR_MEANINGS: Record<number, Meaning> = {
  1: {
    meaning: "Estás en un Año Personal 1, el comienzo de un nuevo ciclo de nueve años. Es un tiempo para la siembra, la independencia y la acción audaz. La energía te impulsa a iniciar nuevos proyectos, a tomar la iniciativa y a definir quién quieres ser en esta nueva etapa. Es un año para ser valiente, original y para enfocarte en tus propias metas sin depender de los demás. Lo que comiences ahora tendrá un impacto significativo en los próximos nueve años de tu vida. Es el momento de ser el pionero de tu propio destino.",
    lightAndShadow: "En luz, este año trae una oleada de nueva energía, oportunidades y la confianza para perseguir tus sueños. Te sentirás motivado y lleno de ideas. En sombra, puedes sentirte solo, impaciente o abrumado por la presión de tener que empezar de nuevo. La energía puede ser tan fuerte que te lleve a tomar decisiones impulsivas o a ser egoísta en tu búsqueda de independencia. El desafío es canalizar esta poderosa energía de inicio con claridad y propósito.",
    tip: "Haz una lista clara de tus metas para este nuevo ciclo. No tengas miedo de empezar de cero en un área de tu vida que ya no te satisface. Toma decisiones por ti mismo y confía en tu instinto. Inscríbete en un nuevo curso, lanza ese proyecto que tienes en mente o simplemente atrévete a hacer algo que nunca has hecho antes. Sé tu propio líder este año y planta las semillas de tu futuro con intención."
  },
  2: {
    meaning: "Después del impulso del año 1, el Año Personal 2 te invita a la paciencia, la cooperación y el desarrollo de tus relaciones. Es un año para cultivar lo que sembraste, no para forzar el crecimiento. La energía se enfoca en la diplomacia, el trabajo en equipo y la conexión emocional. Tu intuición estará muy agudizada. Es un tiempo para escuchar, para ser receptivo y para construir puentes. Las asociaciones, tanto personales como profesionales, serán un tema central. La clave de este año es la paciencia y la fe en el proceso.",
    lightAndShadow: "En luz, este año puede traer nuevas amistades, alianzas estratégicas o el fortalecimiento de una relación amorosa. Te sentirás más empático y conectado. En sombra, puedes experimentar hipersensibilidad, dudas e indecisión. La energía lenta puede frustrarte si esperas resultados rápidos. Puedes volverte demasiado dependiente de la opinión de los demás o evitar confrontaciones necesarias. El desafío es ser cooperativo sin perder tu propio centro.",
    tip: "Practica la escucha activa en todas tus conversaciones. Colaborar en proyectos en lugar de intentar hacerlo todo solo. Dedica tiempo de calidad a tus relaciones importantes. Confía en tu intuición; si algo no se siente bien, probablemente no lo sea. Sé paciente con tus proyectos; están germinando bajo tierra. La meditación y las actividades tranquilas te ayudarán a sintonizar con la energía sutil de este año."
  },
  3: {
    meaning: "Estás en un Año Personal 3, un tiempo de expansión, creatividad y vida social. La energía de este año es ligera, optimista y expresiva. Es el momento perfecto para comunicar tus ideas, socializar y disfrutar de la vida. Tu creatividad estará en su punto más alto, por lo que es ideal para embarcarte en pasatiempos artísticos o para encontrar soluciones imaginativas a los problemas. La alegría y el entusiasmo son tus guías. Es un año para brillar, para conectar con la gente y para expresar tu verdad con autenticidad y carisma.",
    lightAndShadow: "En luz, este año puede ser increíblemente divertido, social y productivo a nivel creativo. Te sentirás inspirado y magnético. En sombra, la energía puede volverse dispersa, llevándote a empezar muchas cosas sin terminar ninguna. Puedes caer en la superficialidad, el drama o el gato excesivo. Tu optimismo puede hacer que evites enfrentar emociones o responsabilidades importantes. El desafío es canalizar tu energía expresiva de manera constructiva.",
    tip: "¡Diviértete! Acepta invitaciones sociales y organiza encuentros. Inscríbete en una clase de arte, escritura, baile o teatro. Expresa tus sentimientos abiertamente, ya sea hablando con amigos o llevando un diario. Cuida tu apariencia y viste de una manera que te haga sentir alegre y creativo. Enfócate en terminar al menos un proyecto creativo este año. Usa tu don de la comunicación para inspirar y elevar a los demás."
  },
  4: {
    meaning: "El Año Personal 4 te pide que te pongas manos a la obra. Después de la expansión del año 3, es el momento de construir, organizar y crear bases sólidas para tu futuro. La energía de este año es práctica, disciplinada y requiere un esfuerzo constante. Es un tiempo para enfocarte en tu trabajo, tus finanzas y tu salud. La planificación, el orden y la atención al detalle serán tus mejores herramientas. Lo que construyas este año con dedicación y perseverancia será duradero y te dará seguridad en los años venideros.",
    lightAndShadow: "En luz, este es un año increíblemente productivo en el que puedes lograr avances significativos en tu carrera y tus finanzas. Te sentirás enfocado y capaz. En sombra, la energía puede sentirse pesada, restrictiva y llena de trabajo duro sin recompensa inmediata. Puedes sentirte frustrado por el lento progreso o caer en el exceso de trabajo hasta el agotamiento. La rigidez y la resistencia al cambio son los mayores peligros.",
    tip: "Crea un plan detallado para tus metas anuales y divídelo en pasos mensuales y semanales. Organiza tus finanzas y crea un presupuesto. Establece una rutina de ejercicio y alimentación saludable. Sé disciplinado y cumple con tus compromisos. No busques atajos; el trabajo duro será recompensado. Recuerda también programar tiempo para el descanso para mantener tu energía."
  },
  5: {
    meaning: "Prepárate para el movimiento, porque el Año Personal 5 trae consigo cambio, aventura y una sensación de liberación. Después del trabajo duro del año 4, el universo te invita a romper con la rutina y a explorar nuevas posibilidades. Es un año para viajar, mudarse, cambiar de trabajo o simplemente probar cosas nuevas. La energía es dinámica, impredecible y llena de oportunidades inesperadas. La adaptabilidad y la apertura mental son claves. Es un tiempo para vivir con los cinco sentidos y abrazar la libertad.",
    lightAndShadow: "En luz, este año puede ser emocionante, liberador y lleno de crecimiento personal. Conocerás gente nueva y vivirás experiencias inolvidables. En sombra, la energía del cambio puede generar ansiedad e inestabilidad. Puedes caer en la impulsividad, la inconsistencia y los excesos. El desafío es usar esta libertad de manera constructiva y no como una excusa para huir de la responsabilidad.",
    tip: "Di 'sí' a las oportunidades inesperadas. Si tienes la oportunidad de viajar, hazlo. Aprende algo nuevo y fuera de tu zona de confort. Haz cambios en tu entorno, como redecorar tu casa. Sé flexible con tus planes. Comunícate y socializa. Practica el desapego de los resultados y fluye con los cambios. Este es un año para experimentar, no para planificar en exceso."
  },
  6: {
    meaning: "El Año Personal 6 centra su energía en el hogar, la familia y las responsabilidades afectivas. Es un tiempo para nutrir tus relaciones, embellecer tu entorno y asumir un rol de servicio en tu comunidad. Los temas de amor, matrimonio, familia y amistad serán prioritarios. La energía te pide que busques el equilibrio y la armonía en tu vida doméstica. Es un año para sanar viejas heridas familiares, para comprometerte más profundamente en tus relaciones o para hacer de tu casa un verdadero hogar.",
    lightAndShadow: "En luz, este año puede traer un profundo sentido de pertenencia, amor y satisfacción en tus relaciones. Es un año ideal para casarse, tener hijos o fortalecer lazos familiares. En sombra, las responsabilidades pueden sentirse abrumadoras. Pueden surgir conflictos familiares que requieran tu atención. Puedes tender a sacrificarte en exceso por los demás o a volverte controlador en tu afán de 'cuidar'. El desafío es equilibrar tus responsabilidades con tu autocuidado.",
    tip: "Dedica tiempo de calidad a tus seres queridos. Embellece tu hogar; píntalo, compra plantas, hazlo más acogedor. Asume tus responsabilidades con amor, no como una carga. Ofrece tu ayuda en tu comunidad o a un amigo que lo necesite. Trabaja en sanar cualquier conflicto familiar pendiente. Y lo más importante: practica el autocuidado. No puedes cuidar de otros si no te cuidas a ti primero."
  },
  7: {
    meaning: "El Año Personal 7 es una invitación a una pausa sagrada. Es un tiempo para la introspección, el análisis y el crecimiento espiritual. La energía te pide que te alejes del ruido del mundo exterior y te sumerjas en tu mundo interior. Es un año para estudiar, para meditar, para cuestionar tus creencias y para conectar con tu sabiduría interna. No es un año para grandes acciones externas, sino para un profundo trabajo interno. La soledad será tu aliada, y la naturaleza tu santuario. Confía en tu intuición.",
    lightAndShadow: "En luz, este puede ser un año de profundas revelaciones, paz interior y un gran salto en tu evolución espiritual. Te sentirás más sabio y conectado. En sombra, si te resistes a la introspección, puedes sentirte solo, melancólico o incomprendido. La energía puede parecer estancada a nivel material, lo que puede generar ansiedad. Puedes volverte demasiado escéptico o mental, desconectándote de tus emociones.",
    tip: "Dedica tiempo regular a estar a solas. Lee libros que expandan tu mente. Inicia una práctica de meditación o lleva un diario. Pasa mucho tiempo en la naturaleza. Cuestiona tus viejas creencias y busca tu propia verdad. No fuerces los resultados en el mundo exterior; el verdadero trabajo está ocurriendo dentro de ti. Confía en el proceso y permite que tu alma se recargue."
  },
  8: {
    meaning: "Después de la pausa del año 7, el Año Personal 8 te impulsa al mundo material con fuerza y ambición. Es el año del poder, el éxito, la abundancia y la cosecha. La energía te apoya para que tomes el control de tu carrera y tus finanzas. Es un tiempo para ser un líder, para tomar decisiones importantes y para manifestar los resultados de los esfuerzos de los años anteriores. Se te pedirá que te haces cargo de tu poder personal y lo uses con sabiduría e integridad. Es un año de grandes avances y logros.",
    lightAndShadow: "En luz, este puede ser un año de gran éxito financiero, reconocimiento profesional y un profundo sentido de empoderamiento. Cosecharás lo que has sembrado. En sombra, puedes enfrentarte a desafíos relacionados con el poder y el dinero. Puedes volverte demasiado materialista, controlador o adicto al trabajo. La energía puede traer tanto grandes ganancias como grandes pérdidas, dependiendo de cómo la manejes. El desafío es equilibrar el poder material con la integridad espiritual.",
    tip: "Sé audaz y asume roles de liderazgo. Pide ese aumento o lanza ese negocio. Organiza tus finanzas y toma el control de tu economía. Vístete para el éxito y proyecta una imagen de confianza y autoridad. Actúa con integridad en todos tus asuntos. Practica la generosidad; cuanto más das, más recibes. Celebra tus logros y reconoce tu poder para crear la vida que deseas."
  },
  9: {
    meaning: "Estás en un Año Personal 9, el final de un ciclo de nueve años. Es un tiempo de culminación, cierre y liberación. La energía te invita a soltar todo lo que ya no te sirve para hacer espacio para lo nuevo que llegará en tu próximo ciclo. Es un año para perdonar, para dejar ir viejos rencores, trabajos, relaciones o creencias que te han estado frenando. Es también un año de gran compasión y servicio humanitario. La sabiduría y la culminación son los temas clave.",
    lightAndShadow: "En luz, este año puede ser profundamente liberador y sanador. Sentirás una sensación de cierre y de paz al soltar las cargas del pasado. Es un tiempo de gran sabiduría y crecimiento espiritual. En sombra, el proceso de soltar puede ser doloroso y emocional. Puedes sentirte melancólico, cansado o reacio a dejar ir el pasado. Pueden surgir finales inesperados que te obliguen a liberarte de lo que ya no es para ti.",
    tip: "Haz una limpieza profunda, tanto física (ordena tu casa y dona lo que no necesitas) como emocional. Escribe cartas de perdón (sin necesidad de enviarlas) a quienes te han herido y a ti mismo. Termina los proyectos pendientes. Pasa tiempo reflexionando sobre las lecciones de los últimos nueve años. Involúcrate en alguna forma de servicio o voluntariado. Confía en que cada final es la preparación para un nuevo y brillante comienzo."
  },
  11: {
    meaning: "Un Año Personal 11 es una vibración maestra de intuición, despertares espirituales e inspiración. Es un año altamente sensible y psíquico, que actúa como un puente entre lo consciente y lo subconsciente. Sentirás un fuerte tirón hacia tu verdad interior y tu camino espiritual. Este año no se trata de acción material, sino de recibir guía divina, confiar en tu intuición e inspirar a otros con tu visión única. Es un año de profundas revelaciones personales y conciencia elevada.",
    lightAndShadow: "En luz, puedes experimentar poderosas percepciones psíquicas, avances creativos y un profundo sentido de propósito. Te conviertes en un canal de inspiración. En sombra, la intensa energía puede provocar tensión nerviosa, ansiedad y sentirte abrumado o desconectado de la realidad. Podrías luchar con la duda o sentir que tus ideales están demasiado lejos del mundo práctico.",
    tip: "La meditación, llevar un diario y pasar tiempo en la naturaleza son esenciales este año para manejar la intensa energía. Confía en tus instintos por encima de todo. Encuentra una salida creativa para expresar el torrente de inspiración que recibirás. Rodéate de un entorno pacífico y de personas que apoyen tu viaje espiritual. Tu misión este año es ser un faro de luz."
  },
  22: {
    meaning: "El Año Personal 22 es el año del 'Maestro Constructor', con un inmenso potencial de manifestación. Combina la visión intuitiva del 11 con la energía práctica y terrenal del 4. Este es un año para tomar tus sueños más grandes y comenzar a construirlos en una realidad tangible. La energía apoya proyectos a gran escala, liderazgo y la creación de algo de valor duradero que pueda beneficiar a muchos. Es un año de acción disciplinada guiada por un propósito superior.",
    lightAndShadow: "En luz, tienes el poder de lograr cosas extraordinarias, convirtiendo ideales en formas concretas con eficiencia y visión. Es un año de logros y empoderamiento increíbles. En sombra, la presión de este número puede ser inmensa, lo que lleva al estrés y a sentirse abrumado. Podrías dudar de tu capacidad para manejar una misión tan grande o, por el contrario, usar tu poder de manera controladora o manipuladora si no está alineado con el servicio.",
    tip: "Piensa en grande, pero empieza poco a poco. Desglosa tu gran visión en pasos prácticos y manejables. Tu disciplina es clave. Colabora con otros que compartan tu visión; no tienes que construir tu imperio solo. Mantente conectado con el 'porqué' detrás de tus metas para asegurar que tu trabajo sirva a un bien mayor. Este es el año para ser el arquitecto de tus sueños."
  },
  33: {
    meaning: "Un Año Personal 33 es el del 'Maestro del Amor y la Sanación', el más cargado espiritualmente de los ciclos. Tu enfoque este año se desplaza hacia el servicio compasivo, la enseñanza y la sanación. Es un tiempo de profunda conexión emocional y responsabilidad hacia los demás. La energía te llama a ser un guía, un consejero y una fuente de amor incondicional. Tu expresión creativa (3) se amplifica y se pone al servicio de tu comunidad y seres queridos (6). Es un año de profunda apertura del corazón y entrega desinteresada.",
    lightAndShadow: "En luz, te conviertes en una poderosa fuerza de sanación e inspiración en el mundo. Tu compasión puede tocar muchas vidas y encuentras una inmensa alegría en el servicio. En sombra, el peso de la responsabilidad puede ser abrumador, llevándote al auto-sacrificio hasta el punto del martirio. Podrías volverte demasiado idealista o perfeccionista en tu deseo de 'arreglar' a todos y todo. El desafío es servir desde una copa llena, no vacía.",
    tip: "Tu autocuidado es innegociable este año. Debes nutrirte a ti mismo primero para poder nutrir a los demás de manera efectiva. Establece límites firmes para proteger tu energía. Usa tus talentos creativos para expresar tu mensaje de amor y sanación. Concéntrate en enseñar con el ejemplo. Tu mayor regalo este año es tu presencia alegre y amorosa, no tu sacrificio."
  }
};
